### ISSUE TITLE
Unable to use Web App Deployment

### ISSUE THREAD

**Issue by nilsanderspersson** [JetBrains/azure-tools-for-intellij#898]
After the update to version 4 (now using 4.1), I can no longer publish to the Web App with dotnet 8. Firstly, it just says Runtime: UNKNOWN. When I then try to publish, it gets stuck on "Trying to deploy artifact to [myserver]". When I check the publishing log in Azure, it now says "OneDeploy," and it hangs there until I cancel the publication in Rider. Before version 4, this process only took a few minutes, and the log indicated that it was published as "Created via a push deployment." I need to resolve this because we currently can't publish at all. I've tried installing all versions from 4.0.0 to 4.1.0.
![Azure 2](https://github.com/user-attachments/assets/d562771b-c6d1-4456-b972-d60c0ed08ddb)
![Azure](https://github.com/user-attachments/assets/63097b04-3b97-4058-adaa-007ddf78e3a1)
![Rider 2](https://github.com/user-attachments/assets/eb40dacd-4bf1-471e-81fa-beda1b0356b9)
![Rider](https://github.com/user-attachments/assets/80566748-b282-4b12-8169-f182431eb76d)

**Comment by nilsanderspersson** [comment]
Is there any way to install version 3 again? Otherwise, I'll unfortunately have to switch to Visual Studio, and I really don't want to do that.

**Comment by nilsanderspersson** [comment]
Version 3 - Deploy took about 1 minute
![before](https://github.com/user-attachments/assets/798a4c03-4159-478f-bb6a-f576d3cbc441)

Version 4 - Failed after 1 hour of deploy
![after](https://github.com/user-attachments/assets/1c14ac40-4439-44b0-b958-d3907421fc12)

**Comment by nilsanderspersson** [comment]
Why is database creation missing, and why does it say RUNTIME: Unknown? Have you released a version that isn't finished? It's a major issue if this version isn't complete and there's no way to roll back to version 3.

**Comment by rafaelldi** [comment]
Hello!

> Firstly, it just says Runtime: UNKNOWN.

This is a known bug, it doesn't affect deploymenet. We will fix it.

> Is there any way to install version 3 again? 

For Rider 2024.2 and later there is no way.

Could you please collect logs (via Help | Collect Logs) and attach them? I will take a look.

**Comment by nilsanderspersson** [comment]
Here are the logs
[rider-logs-20240826-08412712849626547597996844.zip](https://github.com/user-attachments/files/16745047/rider-logs-20240826-08412712849626547597996844.zip)

**Comment by mebrein** [comment]
Same problem here. Unable to deploy to Azure Web App. When looking at the run/debug configurations, the existing profiles show up under Unknown, and this message: Run Configuration Error: Broken configuration due to unavailable plugin or invalid configuration data. I tried rolling back Rider 2024.1.x. But I'm stuck with the Azure Toolkit for Rider 4.1.0. So proceeding now with Visual Studio since I need to deploy now.

**Comment by nilsanderspersson** [comment]
Same here, we publish daily, and now we get to use Visual Studio until this is fixed

**Comment by nilsanderspersson** [comment]
How is this going? Is there a plan to fix this bug?

**Comment by rafaelldi** [comment]
@nilsanderspersson Unfortunately, I can't reproduce this problem on my side. And I don't see any suspicious logs. Maybe there is something in the environment variables; do you have any Azure related variables?

**Comment by mebrein** [comment]
This typically is the 'works on my pc' problem, hard to nail it down this way. To summarize, the old "Publish Web App" are broken and are moved the the "Unknown" folder. But I gave it  another try. I uninstalled the plugin, managed to install the 4.0.0 version. Logged in to Azure, selected all tenants. Now I am able to select one of the web apps (from my tenant). I reinstalled 4.1.0. Now i  In the dropdown to select the Web App I see the web apps, runtime is set to UNKNOWN. But at least I can publish now from within Rider, which helps.

![image](https://github.com/user-attachments/assets/526a277a-debd-44fa-8971-74d9cee0f383)

I also noticed a review for the plugin:

"WARNING They changed the default publish type. Also login using oauth 2.0 seems broken.
The newest 4.1.0 release changed the default publish to AzureWebAppDeploy vs. AzureDotNetWebAppPublish.
The default of AzureWebAppDeploy is to delete all files on the app service! Good we always publish to a dev container first else this would have blown away all our files in our web application in prod."

Maybe this can be taken into account.

**Comment by nilsanderspersson** [comment]
> @nilsanderspersson Unfortunately, I can't reproduce this problem on my side. And I don't see any suspicious logs. Maybe there is something in the environment variables; do you have any Azure related variables?

Note that we are publishing to a slot.

This is our environment variables, nothing strange here.
Have you tried to create a WebAPI project running dotnet 8 to a Azure instance runnning Dotnet 8 (Linux)?

For me, the problem exist on all 3 computers, 1 running Mac OS and 2 running Windows 11.

![Skärmbild 2024-09-02 140154](https://github.com/user-attachments/assets/682df387-0c92-4a26-ac9a-d10d2323ea90)

**Comment by rafaelldi** [comment]
@mebrein 
Yes, unfortunately the old publish configurations don't work because the plugin was rewritten with sctratch and we had to make those changes. I'm sorry for that.

>  runtime is set to UNKNOWN

This is a presentation bug only, it doesn't affect the deployment. We will fix it soon.

> The default of AzureWebAppDeploy is to delete all files on the app service

I've already fixed this issue #904. The fix will be available soon.

> Also login using oauth 2.0 seems broken

I described some details about this bug and possible workarounds here #884. I'm going to further investigate and fix this in the near future.

**Comment by rafaelldi** [comment]
@nilsanderspersson Thanks! Indeed, nothing special. Yes, I've tried dotnet 8 web API applications with Linux OS (and Windows OS too) and a deployment slot. Could you please try deploying a template solution? Also, there should be the deployment logs, could you please check if there is something there?

![image](https://github.com/user-attachments/assets/0bc71455-909c-4c0a-80e7-61e2c637fcd7)

**Comment by nilsanderspersson** [comment]
Hi again
Just updated Rider and installed Azure Plugin 4.1.0 to give it a new try.

There is more problem. When im trying to Login using 0Auth
![0Auth](https://github.com/user-attachments/assets/8a713661-771d-4a23-a3eb-c37a3f58b227)

When trying to login using Device Login
![device_login](https://github.com/user-attachments/assets/a8875010-0a0d-4fa8-8ea9-e406f8d39c60)

Logs
[Uploading rider-logs-20240902-15345212424668939498235561.zip…]()

**Comment by rafaelldi** [comment]
It's known bug #884. It occurs due to a third-party library that is used for authentication in Azure. I'm going to investigate it. As a workaround, you can use the Azure CLI login or disable the authentication cache in the Settings.

![358554037-c6961fad-7332-4314-bbf8-8587905e4e30](https://github.com/user-attachments/assets/962cba4b-3fa7-45d6-951d-3113ecc5291d)

![359003435-3012bc14-7ac3-496d-a744-bc9a3248425d](https://github.com/user-attachments/assets/5f600d4f-af2a-4aef-ba51-ca2ec13484d0)

**Comment by nilsanderspersson** [comment]
Still the same problem, login was success using the Azure CLI but the 0Auth2 and Device doesnt work.
I have also removed all publishing profiles and re-created them. Also deleted the .idea folder in the root.

Then i created a new publishing profile to Azure, select the profile then clicked run.
After 20 minutes, Rider still runs the profile and this is the screenshot from Azure
![Azure logs](https://github.com/user-attachments/assets/2f47396f-0e22-4625-acb4-52308d85da8d)

**Comment by nilsanderspersson** [comment]
Since it unfortunately seems that version 4 of this plugin is not ready for production, is there any way to publish version 3 so that it works with the new version of Rider?

**Comment by nilsanderspersson** [comment]
Trying to retrieve the logs via Azure Explorer in Rider, but it's just stuck on loading, so I can't access them
![Get logs](https://github.com/user-attachments/assets/d9ed3500-1e15-4b5e-84ea-c85c08e939cb)

**Comment by rafaelldi** [comment]
>  is there any way to publish version 3 so that it works with the new version of Rider?

No, unfortunately, due to some breaking changes in the IntelliJ Platform, version 3 is not compatible with Rider 2024.2 and later

**Comment by nilsanderspersson** [comment]
After 30 minutes, the deployment is still in progress
![azure](https://github.com/user-attachments/assets/2b516199-2d7c-41b4-ba1f-22c18847c686)

Same on all three computers. Is there anything more i can provide you with, to help solving this?

**Comment by rafaelldi** [comment]
Can you please try to deploy a simple template `Empty` solution? This will help to understand if the problem is related to some project settings. 

![image](https://github.com/user-attachments/assets/6c11c406-c50a-4e19-bced-29421015b127)

**Comment by nilsanderspersson** [comment]
Hi again, yes the problem seems to be project related. Created a new project and the deployment now succeed.
Is there anyway to toubleshoot why this seems to be project related?

![template](https://github.com/user-attachments/assets/dc8f1a8a-8a1b-4403-a892-2f0e86250b16)

**Comment by nilsanderspersson** [comment]
I think I found the issue. When this deployment succeeded, the Azure logs became available in Rider. The problem was this: A suitable constructor for type 'Jobbs.Infrastructure.Security.JobbAppVersionMiddleware' could not be located.

After fixing that line of code, the deployment went smoothly again.

**Comment by rafaelldi** [comment]
I will think about how to investigate this and get back to you. 

Probably after a failed deployment of your main solution, the deployment logs should be available. I mean that this `loading` status is likely caused by the active deployment.

![363714598-d9ed3500-1e15-4b5e-84ea-c85c08e939cb](https://github.com/user-attachments/assets/9ab9fcee-41d8-4b14-9cb5-f6bfdbcc2a74)

**Comment by nilsanderspersson** [comment]
This is strange, the logs says A suitable constructor for type 'Jobbs.Infrastructure.Security.JobbAppVersionMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

But all services i registrated and the app running fine both in debug and release.
See the attached log 

[logs.txt](https://github.com/user-attachments/files/16838947/logs.txt)

**Comment by rafaelldi** [comment]
A few questions:
- Is it your `Jobbs.Server.dll` or does it come from some library?
- Is it your `Jobbs.Infrastructure.Security.JobbAppVersionMiddleware` or is it from some library?

There should be a log with the `.zip` artifact when you deploy it. You can try copying it somewhere, unzipping it and running it with the same `dotnet Jobbs.Server.dll` command. Will it work?

![image](https://github.com/user-attachments/assets/33b00edb-524c-439b-8ee9-03efc26aad7e)

**Comment by nilsanderspersson** [comment]
Yes, the Jobbs.Server and Jobbs.Infrastructure are our code.
I tried copying the zip file, extracting it, and running dotnet Jobbs.Server.dll, but the application won't start.
However, when I try running it from the bin folder, it works. Could there be something wrong when Rider zips the application?

When i run dotnet Jobbs.Server.dll the console output is nothing
![Skärmbild 2024-09-03 095002](https://github.com/user-attachments/assets/c22f3b14-eefc-414d-80dd-a17c70904f0f)

**Comment by rafaelldi** [comment]
Rider simply uses `dotnet publish` and packs the resulting folder into a zip archive. Do you see the difference between the files?

**Comment by nilsanderspersson** [comment]
Now I've tested more, and the release works from the zip file. It was just that it didn't produce any output, but it starts and works as it should. So it's only when I publish that this error occurs. Do you have any ideas on how I can troubleshoot this further?

**Comment by nilsanderspersson** [comment]
Here is the logs when using Visual Studio
[2024_09_03_lw1sdlwk0006AF_default_docker.log](https://github.com/user-attachments/files/16848357/2024_09_03_lw1sdlwk0006AF_default_docker.log)

Is there anyway to get the startup.sh file?

**Comment by rafaelldi** [comment]
You can use this menu 

![image](https://github.com/user-attachments/assets/670fce64-375d-4e80-8f97-81886b4f18a4)

![image](https://github.com/user-attachments/assets/bec61867-91c4-4359-afff-92042a3d7610)

![image](https://github.com/user-attachments/assets/121afa3e-7a4b-4638-9638-4212b130f5dc)

Also, you could try to run `dotnet Jobbs.Server.dll` from this SSH console

**Comment by lexuanzhou** [comment]
I am having the same issue, the deployment output is just stuck at the Deploying step. According to the deployment center log on Azure, it does deploy succesfully, but it takes way longer than the previous version ( more than 3 mins vs less than 1 min)
<img width="480" alt="image" src="https://github.com/user-attachments/assets/b6a12fb2-3875-4f00-b09d-464d3400fb23">

**Comment by nilsanderspersson** [comment]
Now I have tried everything from step 1. Publishing to Azure 2. After 40 minutes, Rider is still publishing, and in Azure, it says that the application is being built. 3. I stop the publishing in Rider, and after about 20 minutes, Azure has stopped building the application. During this time, I am logged in via SSH and cannot see any files under wwwroot. 4. I retrieve the log, which you can see here.

[logs.txt](https://github.com/user-attachments/files/16861815/logs.txt)

**Comment by nilsanderspersson** [comment]
Is there anything else i can do to help you toubleshoot?

**Comment by rafaelldi** [comment]
I need some time to experiment with some ideas

**Comment by nilsanderspersson** [comment]
Yes, thank you. Please let me know if there is anything else I can do to help.

**Comment by pgillett** [comment]
I've had some "completed" deploys that weren't actually deployed.

I tried many deploys yesterday (after sorting the login etc. issues). First two were fine. However, I made numerous attempts after that. All said deployed successfully, but changes weren't there. Looking at the Azure logs, I'd got two "OneDeploys" yesterday (the ones that had worked), and no record of the others, although it showed one failed deploy. When I looked on the console, it clearly hadn't replaced the files.

Installed R2024.1.6 and 3.50.0.1784-2024.1 Tools this morning, and deployed first time.

This morning the logs show the two that worked yesterday and the latest 3.50 deploy. However, the failed one has disappeared.

**Comment by rafaelldi** [comment]
This PR #909 should probably fix all the problems. I've reverted back to zip deployment. Why did we switch to a different deployment mechanism in the v4 plugin? As you may know, our plugin is a fork of the Microsoft Azure plugin for Java developers, so we use many of the features of the Java plugin. And they use this `OneDeploy` deployment mechanism. But it probably doesn't work well enough for .NET projects (I couldn't find any documentation about what `OneDeploy` is and how it differs from zip-deploy). So I decided to just revert back to v3 behavior. Now everything should work the way it did in the v3 plugin.

I tested on my small projects and it works. But I would ask you to test this plugin build and give me feedback if it works as expected on your real-world projects. Here is the link to the built plugin https://github.com/JetBrains/azure-tools-for-intellij/actions/runs/10719085818/artifacts/1895755740. To install it, just use this menu and choose the `azure-toolkit-for-rider-4.1.3.zip` archive.

I'm really sorry that the v4 plugin has broken your workflows, and I hope the fix helps.

![image](https://github.com/user-attachments/assets/96cbc5e4-a129-4da1-bc96-9e5315ba8509)

**Comment by nilsanderspersson** [comment]
I can confirm that publishing to Azure is now working again with version 4.1.3. Thank you for your help.

**Comment by rafaelldi** [comment]
Thank you for testing. Then I'll publish a new version today.

**Comment by pgillett** [comment]
Have updated to v4.1.3. When I "Deploy to Web App", the Web App: drop down sits with "Loading..." and the spinning wheel.

![image](https://github.com/user-attachments/assets/7a1e1a30-eb0c-426a-8210-48f3c9237f6f)

**Comment by rafaelldi** [comment]
@pgillett Could you please create a new issue, collect logs (via Help | Collect Logs) and attach them to the issue? I'll take a look.
Thank you in advance!

**Comment by thomazngv** [comment]
> Have updated to v4.1.3. When I "Deploy to Web App", the Web App: drop down sits with "Loading..." and the spinning wheel.
> 
> ![image](https://github.com/user-attachments/assets/7a1e1a30-eb0c-426a-8210-48f3c9237f6f)

Did you get it solved? Im having a similar issue, web apps keep loading then empty list.
funny thing is when I login the login page pops up twice, it logs me in fine though. Just the web apps not loading, my co workers intellij azure web apps loads fine

**Comment by dchelstowski** [comment]
> > Have updated to v4.1.3. When I "Deploy to Web App", the Web App: drop down sits with "Loading..." and the spinning wheel.
> > ![image](https://github.com/user-attachments/assets/7a1e1a30-eb0c-426a-8210-48f3c9237f6f)
> 
> Did you get it solved? Im having a similar issue, web apps keep loading then empty list. funny thing is when I login the login page pops up twice, it logs me in fine though. Just the web apps not loading, my co workers intellij azure web apps loads fine

@thomazngv having same problem on my machine, have you resolved it somehow?
